# Form implementation generated from reading ui file '.\forms\olenemer-ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1536, 864)
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(1, 10, 1531, 851))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.al_frame = QtWidgets.QFrame(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.al_frame.sizePolicy().hasHeightForWidth())
        self.al_frame.setSizePolicy(sizePolicy)
        self.al_frame.setMinimumSize(QtCore.QSize(280, 210))
        self.al_frame.setMaximumSize(QtCore.QSize(280, 210))
        self.al_frame.setObjectName("al_frame")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.al_frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 40, 171, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.al_panel = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.al_panel.setContentsMargins(5, 0, 5, 0)
        self.al_panel.setSpacing(4)
        self.al_panel.setObjectName("al_panel")
        self.horizontalLayout_2.addWidget(self.al_frame)
        spacerItem2 = QtWidgets.QSpacerItem(520, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.en_frame = QtWidgets.QFrame(parent=self.layoutWidget)
        self.en_frame.setMinimumSize(QtCore.QSize(280, 210))
        self.en_frame.setMaximumSize(QtCore.QSize(280, 210))
        self.en_frame.setObjectName("en_frame")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.en_frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(50, 60, 160, 80))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.en_panel = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.en_panel.setContentsMargins(5, 0, 5, 0)
        self.en_panel.setSpacing(4)
        self.en_panel.setObjectName("en_panel")
        self.horizontalLayout_2.addWidget(self.en_frame)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Olenemer"))
